### ISSUE TITLE
Error after running truffle test 

### ISSUE THREAD

**Issue by MRANASSPRO** [skiral/gilgamesh-token-contract#2]
I was trying to run this project locally, I followed all the steps mentionned in README.md,
but after running `truffle test`, I got this output : 

```
 1) Contract: TestGilgameshTokenSale "before each" hook: before test:
     Uncaught AssertionError: expected promise to be fulfilled but it was rejected with 'Error: Error: VM Exception while processing transaction: revert'
```
Any cause, solution? 

Thank you.

**Comment by skiral** [comment]
You would need to run `testrpc` in the background before running the unit tests.

**Comment by MRANASSPRO** [comment]
Thanks for the answer, I run `testrpc` in the background, but after trying `test` in the truffle console, I got this error:
```
/home/mranasspro/.nvm/versions/node/v9.11.1/lib/node_modules/truffle/node_modules/mocha/lib/runnable.js:301
    fn(err);
    ^
TypeError: Cannot set property 'state' of undefined
    at /home/mranasspro/.nvm/versions/node/v9.11.1/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:589:20
    at done (/home/mranasspro/.nvm/versions/node/v9.11.1/lib/node_modules/truffle/node_modules/mocha/lib/runnable.js:301:5)
    at /home/mranasspro/.nvm/versions/node/v9.11.1/lib/node_modules/truffle/node_modules/mocha/lib/runnable.js:359:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by skiral** [comment]
Can you switch to Node V8 and try again?

**Comment by MRANASSPRO** [comment]
I tried with node v8 and same problem, why not update this repo working with geth as a RPC
